"""добавил уникальности полям в hotels

Revision ID: 4478017c0849
Revises: afe0b2f49f98
Create Date: 2026-07-13 15:30:01.702791

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4478017c0849"
down_revision: Union[str, Sequence[str], None] = "afe0b2f49f98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_hotel_title_location", "hotels", ["title", "location"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_hotel_title_location", "hotels", type_="unique")
    # ### end Alembic commands ###
